### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by patrickelectric** [miurahr/install-linuxdeploy-action#20]
[build (ubuntu-latest, qhot.AppImage)](https://github.com/patrickelectric/qhot/actions/runs/4398670998/jobs/7702676926)
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: miurahr/install-linuxdeploy-action@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by miurahr** [comment]
Thanks for heading me up. @patrickelectric

**Comment by miurahr** [comment]
fixed in v1.6.0
