### ISSUE TITLE
Could not find file error

### ISSUE THREAD

**Issue by Shatur95** [miurahr/install-linuxdeploy-action#4]
I have the following error when trying to execute your action with default parameters:

```
Download action repository 'miurahr/install-linuxdeploy-action@v1.3.2'
Error: Could not find file '/home/runner/work/_actions/_temp_af8e1d7f-d8d7-4995-b562-9e0885d07e69/_staging/miurahr-install-linuxdeploy-action-0b05ef6/node_modules/.bin/json5'.
```

Machine Ubuntu 18.04.

**Comment by miurahr** [comment]
v1.3.2 seems broken by mistaken on release procedure.

v1 still point to v1.3.1 so please use @v1.3.1 or @v1.

**Comment by Shatur95** [comment]
With @v1.3.1 I have the same issue, but @v1 worked fo me.

**Comment by Shatur95** [comment]
BTW, @v1.3.0 also has the same problem.

**Comment by miurahr** [comment]
@v1.3.3 and @v1 now released with fix.

**Comment by Shatur95** [comment]
Thank you!
I have a question, When I using `dir` input it points to the `<specified-folder>/bin`. Is it expected?

**Comment by miurahr** [comment]
It is also a bug.

**Comment by Shatur95** [comment]
@miurahr, should I open a separate issue for it?

**Comment by Shatur95** [comment]
@miurahr, I noticed that you fixed the bug but made a mistake in the release tag (you used `v.13.3`). CI prints the following error:

```
File not found: '/home/runner/work/_actions/miurahr/install-linuxdeploy-action/v.13.3/dist/index.js'
```

**Comment by miurahr** [comment]
remove v.13.3 tag

**Comment by Shatur95** [comment]
@miurahr, thanks! I tested @v1.3.4 and it works, but the directory problem still exists. My configuration:

```yml
    - name: Install linuxdeploy
      if: matrix.os == 'ubuntu-18.04'
      uses: miurahr/install-linuxdeploy-action@v1.3.4
      with:
        dir: build
        plugins: qt
```

But the files are loaded into `build/bin` instead of `build`.

**Comment by miurahr** [comment]
v1, v1.4.0 and releases branch are tested  https://github.com/miurahr/install-linuxdeploy-action/runs/2310760306?check_suite_focus=true

```
with:
    dir: /home/runner/work/install-linuxdeploy-action/install-linuxdeploy-action
    plugins: qt appimage
```

then log show output path without 'bin';
```
wget -c -nv https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/releases/download/continuous/linuxdeploy-plugin-appimage-x86_64.AppImage -O /home/runner/work/install-linuxdeploy-action/install-linuxdeploy-action/linuxdeploy-plugin-appimage-x86_64.AppImage
```

and succeeded  just to call

```
linuxdeploy-x86_64.AppImage --list-plugins
```
and it works because PATH is set properly.

**Comment by Shatur95** [comment]
Thank you a lot, works as expected now!
